### PR TITLE
Fix custom tag documentation

### PR DESCRIPTION
**Pull request by loranger**
Mandatories abstract implementations were missing

### CODE REVIEW

**Comment by butschster** [comment]
Could you provide unittest for this changing?

**Comment by loranger** [comment]
I'm afraid I can't test mandatories interface methods are well documented in readme file

**Comment by loranger** [comment]
@butschster I can't find existing unit test for documentation changes, can you please show me the kind of test you need

**Comment by butschster** [comment]
> @butschster I can't find existing unit test for documentation changes, can you please show me the kind of test you need

Oh sorry. Yesterday I didn't notice that you fixed docs))) My fault.

But it would be great if you cover with test this changing https://github.com/butschster/LaravelMetaTags/blob/master/src/MetaTags/Entities/Webmaster.php#L25

**Comment by butschster** [comment]
@loranger Thank you for help!

**Comment by loranger** [comment]
> But it would be great if you cover with test this changing https://github.com/butschster/LaravelMetaTags/blob/master/src/MetaTags/Entities/Webmaster.php#L25

[Done](https://github.com/butschster/LaravelMetaTags/pull/43) !

**Pull request merged**
